### PR TITLE
Use simpler google maven repo syntax

### PR DESCRIPTION
**Pull request by licaon-kter**
ref https://gitlab.com/fdroid/fdroiddata/-/commit/234a7b29b6b671e9919de6d9f49364d5e097a685#note_1088196112

### CODE REVIEW

**Comment by bubelov** [comment]
@licaon-kter does it cause any issues with F-Droid?

The origial lines were `mavenCentral()` and `google()`, but then I thought maybe it doesn't worth aliasing. Exposing those URLs makes this script more transparent in a way that it clearly shows where it's going to pull its deps from. Also, there is no alias for JitPack, so it looked kind of inconsistent. I have no strong opinions on that though, if it bothers some linter script or makes things less convenient on F-Droid side, we can totally replace both of those URLs with their built-in aliases.

**Comment by licaon-kter** [comment]
F-Droid has a hardcoded list of trusted maven repos. Your URL might be pointing to the same repo yet it does not match what's trusted.

If it does not match it is rejected and the app is not built.

**Comment by bubelov** [comment]
@licaon-kter I see. What about Maven Central URL? Should it be changed to `mavenCentral()` or F-Droid can recognize it by it's URL? I mean the line above `google()`:

```
maven("https://repo.maven.apache.org/maven2/")
```

**Comment by licaon-kter** [comment]
Can be changed too :)

**Comment by bubelov** [comment]
@licaon-kter should I push a new release or it will go trough automatically after the merge?

**Comment by licaon-kter** [comment]
I've updated the recipe, no more actions needed: https://gitlab.com/fdroid/fdroiddata/-/commit/573669f667781f716b00b8d0bf829cfc85773b85 ;)

**Pull request merged**
